### ISSUE TITLE
How to switch buttons ?

### ISSUE THREAD

**Issue by octavegraf** [DuroSoft/XJoy#47]

**Comment by Cyberblader** [comment]
I would also like to know this, as I have 0 programming and coding experience and have no idea how to remap the buttons to the traditional Nintendo Layout

**Comment by sam0x17** [comment]
Unfortunately it is impossible to change these without having someone do it for you or learning some basic C++ development skills as the values are hard-coded right now and the person working on the configuration file feature abandoned it. Always a great time to learn though!

**Comment by melodypink** [comment]
I know this is old, but this is for anyone else coming by here in the future. I have no real coding experience, but I managed to get something working, so I figured I'd share. Parts of this feel wrong, but it works, so until someone who actually knows what they are doing comes along to share their wisdom, this is what I've got. (Don't forgot your drivers if you need them)

1. Download a program called Microsoft Visual Studio. When you install it, you will be prompted to add "workloads". I'll be honest, I don't remember which one I ended up needing, but you can skip them for now, and when you open the project later, it will let you add the one you need.
2. Download the XJoy files, on the main page hit the green "code" button and download the zip. Unzip this where you want to store XJoy.
3. Open Visual Studio. Hit File>Open>Folder and select the XJoy-master folder
4. Open XJoy.cpp from the "Solution Explorer" window on the right. (You will probably see the prompt to add the necessary workload)
5. Search (control+F) for "case right_buttons". Go to the third instance of this phrase. You should see > ` case R_BUT_A:
   xbox->right_buttons = xbox->right_buttons | XUSB_GAMEPAD_B;
   break;
 case R_BUT_B:
   xbox->right_buttons = xbox->right_buttons | XUSB_GAMEPAD_A;
   break;
 case R_BUT_X:
   xbox->right_buttons = xbox->right_buttons | XUSB_GAMEPAD_Y;
   break;
 case R_BUT_Y:
   xbox->right_buttons = xbox->right_buttons | XUSB_GAMEPAD_X;
   break;`

6. Swap XUSB_GAMEPAD_B with XUSB_GAMEPAD_A, and XUSB_GAMEPAD_X with XUSB_GAMEPAD_Y. Save.
7. Open XJoy.sln from the Solution Explorer. If you, like me, accidentally downloaded Visual Studio 2022 instead of an older version, you will be prompted to "Retarget Solution". If it pops open, just click Okay. If you lose it, on the top menu, select Project>Retarget Solution and then hit Okay. It is possible this breaks something and you might be better off just using the older version, but it seems fine.
8. From the menu, select Build>Build XJoy
9. In File Explorer, open XJoy-master>Debug, and copy the application and paste it into XJoy-master>XJoy.
10. Congratulations, you can now run XJoy from this application with the buttons realigned.
